HT_18/product_parsing/product_parsing/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scraper.urls', namespace='scraper')),
]

HT_18/product_parsing/scraper/urls.py
from django.urls import path
from scraper import views

app_name = 'scraper'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_product/', views.add_product, name='add_product'),
    path('show_all_products/<int:pk>/', views.product_data, name='product_data'),
    path('show_my_products/', views.show_my_products, name='show_my_products'),
    path('scraper/', views.scraper_data, name='scraper_data'),
]

HT_18/product_parsing/scraper/models.py
from django.db import models


class Product(models.Model):
    product_id = models.CharField(max_length=15)
    brand_name = models.CharField(max_length=50)
    product_name = models.CharField(max_length=255)
    category = models.CharField(max_length=255,)
    discounted_price = models.CharField(max_length=10)
    product_link = models.CharField(max_length=255)


class ScrapingTask(models.Model):
    input_string = models.CharField(max_length=1000)

HT_18/product_parsing/scraper/forms.py
from django import forms


class AddProductsForm(forms.Form):
    id_string = forms.CharField(widget=forms.Textarea)

HT_18/product_parsing/scraper/views.py
from django.shortcuts import get_object_or_404, redirect, render
from subprocess import Popen

from .models import ScrapingTask, Product


def index(request):
    return render(request, 'index.html', {'title': 'Main'})


def add_product(request):
    return render(request, 'add_product.html', {'title': 'Add product'})


def product_data(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'product.html', {'product': product})


def scraper_data(request):
    response = request.GET.get('id_string')
    ScrapingTask.objects.create(input_string=response)
    Popen(['python3', 'subscraper.py'])
    return redirect('scraper:add_product')


def show_my_products(request):
    return render(request, 'show_my_products.html', {'products': Product.objects.all()})

HT_18/product_parsing/scraper/templates/scraper/add_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        nav {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            background-color: rgba(29, 19, 222, 0.65);
            padding: 10px;
            display: flex;
            justify-content: center;
            border-radius: 5px;
            z-index: 1000;
        }

        .button {
            background-color: rgb(139, 153, 218);
            width: 125px;
            border-radius: 6px;
            border: 1px;
            color: white;
            padding: 5px 5px;
            text-align: center;
            text-decoration: none;
            display: block;
            font-size: 14px;
            transition-duration: 0.4s;
            cursor: pointer;
            margin-right: 10px;
        }

        .button:hover {
            background-color: rgba(94, 204, 176, 0.926);
            color: white;
        }

        .nav-link {
            text-decoration: none;
            color: white;
        }

        .header {
            padding: 50px;
            text-align: center;
        }

        .add-product {
            margin-left: 100px;
            margin-top: 25px;
        }

        .show-info {
            margin-left: 505px;
            margin-top: 20px;
        }

        .footer {
            background-color: #6c60c7ab;
            color: white;
            padding: 20px;
            width: 100%;
            text-align: center;
            position: fixed;
            bottom: 0;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>FIND YOUR PRODUCT</h1>
    </div>

    <nav>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:index' %}">HOME</a></button>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:add_product' %}">ADD PRODUCT</a></button>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:show_my_products' %}">MY PRODUCTS</a></button>
    </nav>

    <div class="add-product">
        <form action="{% url 'scraper:scraper_data' %}">
            <label>
                <h2>Enter your product</h2>
                <textarea name="id_string" rows="10" cols="60" placeholder="Enter ID separated by comma"></textarea>
            </label>
            <br>
            <br>
            <input type="submit" value="Find">
        </form>
    </div>
    <h4>Visit MY PRODUCTS for more information</h4>
    <div class="footer">
        2024 Find your product. Contacts: terentyevamarie@gmail.com
    </div>


</body>

</html>

HT_18/product_parsing/scraper/templates/scraper/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        nav {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            background-color: rgba(29, 19, 222, 0.65);
            padding: 10px;
            display: flex;
            justify-content: center;
            border-radius: 5px;
            z-index: 1000;
        }

        .button {
            background-color: rgb(139, 153, 218);
            width: 125px;
            border-radius: 6px;
            border: 1px;
            color: white;
            padding: 5px 5px;
            text-align: center;
            text-decoration: none;
            display: block;
            font-size: 14px;
            transition-duration: 0.4s;
            cursor: pointer;
            margin-right: 10px;
        }

        .button:hover {
            background-color: rgba(38, 30, 152, 0.926);
            color: white;
        }

        .nav-link {
            text-decoration: none;
            color: white;
        }

        #content {
            margin-top: 60px;
        }

        .container {
            text-align: center;
            margin-top: 50px;
        }

        .instructions {
            font-size: 30px;
            margin-bottom: 20px;
        }

        .circle {
            width: 200px;
            height: 200px;
            background-color: hsl(161, 55%, 67%);
            border-radius: 100%;
            display: inline-block;
            margin: 0 60px;
            position: relative;
        }

        .rectangle {
            background-color: #ecf0f1f1;
            border-radius: 100%;
            padding: 10px;
            margin-top: 80px;
        }

        .circle-text {
            position: absolute;
            bottom: -50px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 18px;
        }

        .footer {
            background-color: #6c60c7ab;
            color: white;
            padding: 20px;
            width: 100%;
            text-align: center;
            position: fixed;
            bottom: 0;
        }

        .header {
            padding: 50px;
            text-align: center;
        }
    </style>
</head>

<body>

    <nav>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:index' %}">HOME</a></button>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:add_product' %}">ADD PRODUCT</a></button>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:show_my_products' %}">MY PRODUCTS</a></button>
    </nav>

    <div class="header">
        <h1>FIND YOUR PRODUCT</h1>
    </div>

    <div id="content">
    </div>

    <div class="container">
        <div class="instructions">INSTRUCTIONS</div>

        <div class="circle">
            <div class="rectangle">
                Home button
            </div>
            <div class="circle-text">Returns to the home page</div>
        </div>

        <div class="circle">
            <div class="rectangle">
                Add product button
            </div>
            <div class="circle-text">Searches for/adds product </div>
        </div>

        <div class="circle">
            <div class="rectangle">
                My products button
            </div>
            <div class="circle-text">Shows all your products</div>
        </div>
    </div>

    <div class="footer">
        2024 Find your product. Contacts: terentyevamarie@gmail.com
    </div>

</body>

</html>

HT_18/product_parsing/scraper/templates/scraper/product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ product.product_name }} Details</title>
</head>
<style>
    #product-details {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 60%;
        margin-left: 650px;
        margin-top: -325px;
    }

    #product-details td,
    #product-details th {
        border: 3px solid rgba(102, 205, 176, 0.62);
        padding: 8px;
    }

    #product-details tr:hover {
        background-color: rgba(102, 205, 176, 0.62);
    }

    #product-details th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #726fd9;
        color: white;
    }

    .product-info {
        margin-left: -500px;
        margin-top: 300px;
    }

    .back {
        margin-left: 150px;
        margin-top: 10px;
    }

    .back-link {
        text-decoration: none;
        display: inline-block;
        padding: 10px 20px;
        background-color: rgba(102, 205, 176, 0.62);
    }

    body {
        margin: 0;
        padding: 0;
        height: 100%;
    }

    nav {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        background-color: rgba(29, 19, 222, 0.65);
        padding: 10px;
        display: flex;
        justify-content: center;
        border-radius: 5px;
        z-index: 1000;
    }

    .button {
        background-color: rgb(139, 153, 218);
        width: 125px;
        border-radius: 6px;
        border: 1px;
        color: white;
        padding: 5px 5px;
        text-align: center;
        text-decoration: none;
        display: block;
        font-size: 14px;
        transition-duration: 0.4s;
        cursor: pointer;
        margin-right: 10px;
    }

    .button:hover {
        background-color: rgba(30, 75, 152, 0.926);
        color: white;
    }

    .nav-link {
        text-decoration: none;
        color: white;
    }

    #content {
        margin-top: 60px;
    }

    .header {
        padding: 50px;
        text-align: center;

    }
</style>

<body>
    <nav>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:index' %}">HOME</a></button>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:add_product' %}">ADD PRODUCT</a></button>
        <button class="button"> <a class="nav-link" href="{% url 'scraper:show_my_products' %}">MY PRODUCTS</a></button>
    </nav>

    <div class="header">
        <h1>FIND YOUR PRODUCT</h1>
    </div>

    <div class="product-info">
        <table id="product-details">
            <tr>
                <th>Product ID:</th>
                <td>{{ product.product_id }}</td>
            </tr>
            <tr>
                <th>Brand:</th>
                <td>{{ product.brand_name }}</td>
            </tr>
            <tr>
                <th>Product Name:</th>
                <td>{{ product.product_name }}</td>
            </tr>
            <tr>
                <th>Category:</th>
                <td>{{ product.category }}</td>
            </tr>
            <tr>
                <th>Price:</th>
                <td>{{ product.discounted_price }}</td>
            </tr>
            <tr>
                <th>Product URL:</th>
                <td><a class="site-link" href="{{ product.product_link }}" target="_blank">{{ product.product_link
                        }}</a>
                </td>
            </tr>
        </table>
    </div>

    <div class="back">
        <button><a class="back-link" href="{% url 'scraper:show_my_products' %}">Back</a></button>
    </div>

</body>

</html>

HT_18/product_parsing/scraper/templates/scraper/show_my_products.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{{ title }}</title>

  <style>
    body {
      margin: 0;
      padding: 0;
      height: 100%;
    }

    nav {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: rgba(29, 19, 222, 0.65);
      padding: 10px;
      display: flex;
      justify-content: center;
      border-radius: 5px;
      z-index: 1000;
    }

    .button {
      background-color: rgb(139, 153, 218);
      width: 125px;
      border-radius: 6px;
      border: 1px;
      color: white;
      padding: 5px 5px;
      text-align: center;
      text-decoration: none;
      display: block;
      font-size: 14px;
      transition-duration: 0.4s;
      cursor: pointer;
      margin-right: 10px;
    }

    .button:hover {
      background-color: rgba(30, 75, 152, 0.926);
      color: white;
    }

    .nav-link {
      text-decoration: none;
      color: white;
    }

    .text {
      margin-left: 550px;
      margin-top: 70px;
    }

    .info {
      margin-left: 550px;
      margin-top: -10px;
    }

    a.product:link {
      background-color: rgba(12, 58, 203, 0.6);
      color: #090002;
      padding: 5px;
      margin: -5px;
      text-align: left;
      text-decoration: none;
      display: table;
      border-radius: 8px;
    }

    a.product:visited {
      background-color: rgba(141, 238, 221, 0.54);
      color: #090002;
      padding: 5px;
      margin: -5px;
      text-align: left;
      text-decoration: none;
      display: table;
      border-radius: 8px;
    }

    a.product:hover {
      background-color: rgba(248, 248, 248, 0.49);
      color: rgb(9, 0, 2);
    }

    .footer {
      background-color: #6c60c7ab;
      color: white;
      padding: 20px;
      width: 100%;
      text-align: center;
      position: fixed;
      bottom: 0;
    }
  </style>
</head>

<body>
  <nav>
    <button class="button"> <a class="nav-link" href="{% url 'scraper:index' %}">HOME</a></button>
    <button class="button"> <a class="nav-link" href="{% url 'scraper:add_product' %}">ADD PRODUCT</a></button>
    <button class="button"> <a class="nav-link" href="{% url 'scraper:show_my_products' %}">MY PRODUCTS</a></button>
  </nav>

  <div class="text">
    <h1>All products list</h1>
  </div>

  <div class="info">
    {% for product in products %}
    <a class="product" href="{% url 'scraper:product_data' pk=product.pk %}" target="_parent">
      <b> {{ product.id }}.</b> {{ product.product_name }} - <b>{{ product.discounted_price }}</b></a><br>
    {% endfor %}
  </div>
  <div class="footer">
    2024 Find your product. Contacts: terentyevamarie@gmail.com
  </div>

</body>

</html>